theme: jekyll-theme-minimal
title: Daisuke Adachi
logo: "assets/images/03- Daisuke Adachi narrow.jpg"
#description: Ph.D candidate at Yale University, Department of Economics
#email: daisuke.adachi@yale.edu